// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvhvyanvirlawruucsjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2aHZ5YW52aXJsYXdydXVjc2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDg4MTUsImV4cCI6MjA1ODkyNDgxNX0.BNKrf7Pv5g54d9iewqLxbf9oYIYWtOgKSA-KfJCId7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// async function signUp(email, password) {
//     const { user, session, error } = await supabase.auth.signUp({
//       email,
//       password,
//       options: {
//         redirectTo: 'http://localhost:8080/verify-email', // Explicitly set the redirect URL
//       },
//     });
  
//     if (error) {
//       console.error('Error signing up:', error);
//     } else {
//       console.log('Sign up successful:', { user, session });
//     }
//   }

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);